const products = [
  {
    id: 0,
    name: "Syltherine",
    kind: "Stylish cafe chair",
    price: 358.85,
    discount: 30,
    dellPrice: 450.67,
    img: "./imges/product 1.png",
    isNew: false,
  },
  {
    id: 1,
    name: "Leviosa",
    kind: "Stylish cafe chair",
    price: 438.85,
    discount: 0,
    dellPrice: 0,
    img: "./imges/product 2.png",
    isNew: false,
  },
  {
    id: 2,
    name: "Lolito",
    kind: "Luxury big sofa",
    price: 2499.99,
    discount: 50,
    dellPrice: 1297.49,
    img: "./imges/product 3.png",
    isNew: false,
  },
  {
    id: 3,
    name: "Respira",
    kind: "Outdoor bar table and stool",
    price: 358.85,
    discount: 0,
    dellPrice: 0,
    img: "./imges/product 4.png",
    isNew: true,
  },
  {
    id: 4,
    name: "Grifo",
    kind: "Night lamp",
    price: 299.99,
    discount: 0,
    dellPrice: 0,
    img: "./imges/product 5.png",
    isNew: false,
  },
  {
    id: 5,
    name: "Muggo",
    kind: "Small mug",
    price: 565.68,
    discount: 0,
    dellPrice: 0,
    img: "./imges/product 6.png",
    isNew: true,
  },
  {
    id: 6,
    name: "Pingky",
    kind: "Cute bed set",
    price: 1999.99,
    discount: 50,
    dellPrice: 999.49,
    img: "./imges/product 7.png",
    isNew: false,
  },
  {
    id: 7,
    name: "Potty",
    kind: "Minimalist flower pot",
    price: 558.85,
    discount: 0,
    dellPrice: 0,
    img: "./imges/product 8.png",
    isNew: true,
  },
  {
    id: 8,
    name: "Luxury Sofa",
    kind: "Comfortable leather sofa",
    price: 1299.99,
    discount: 0,
    dellPrice: 1599.99,
    img: "./imges/product 10.png",
    isNew: true,
  },
  {
    id: 9,
    name: "Modern Dining Table",
    kind: "Elegant glass dining table",
    price: 899.5,
    discount: 10,
    dellPrice: 999.5,
    img: "./imges/product 12.png",
    isNew: false,
  },
  {
    id: 10,
    name: "Classic Wooden Bed",
    kind: "Solid wood bed frame",
    price: 749.75,
    discount: 0,
    dellPrice: 0,
    img: "./imges/product 11.png",
    isNew: true,
  },
  {
    id: 11,
    name: "Stylish Office Chair",
    kind: "Ergonomic office chair",
    price: 359.99,
    discount: 11,
    dellPrice: 429.99,
    img: "./imges/product 13.png",
    isNew: false,
  },
  
];
